src/app/projects/forms.py
"""

app/projects/forms.py

written by: Oliver Cordes 2019-02-04
changed by: Oliver Cordes 2020-02-29

"""


from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, \
                    SubmitField, TextAreaField, RadioField, \
                    SelectField
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms.validators import ValidationError, DataRequired, \
                               Email, EqualTo, Length
from app.models import Project


class CreateProjectForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    project_type = RadioField('Type', choices=[('0','Image'),('1','Animation')], validators=[DataRequired()])
    version = SelectField(u'Povray version', choices=[('3.7', '3.7'), ('3.8', '3.8'), ('3.6', '3.6')])
    is_public = BooleanField('Public' )
    submit = SubmitField('Create')


    def validate_name(self, name):
        project = Project.query.filter_by(name=name.data).first()
        if project is not None:
            raise ValidationError('Please use a different project name.')


class UpdateProjectForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    project_type = RadioField('Type', choices=[('0','Image'),('1','Animation')], validators=[DataRequired()])
    version = SelectField(u'Povray version', choices=[('3.7', '3.7'), ('3.8', '3.8'), ('3.6', '3.6')])
    is_public = BooleanField('Public' )

    update = SubmitField('Update')


class ManageBaseFileForm(FlaskForm):
    remove = SubmitField('Remove')


class ManageImageForm(FlaskForm):
    remove = SubmitField('Remove')


class ProjectListForm(FlaskForm):
    remove = SubmitField('Remove')
    create = SubmitField('+ Add New')

src/app/projects/__init__.py
"""
app/projects/__init__.py


written by: Oliver Cordes 2019-02-04
changed by: Oliver Cordes 2019-03-12

"""

from flask import Blueprint

bp = Blueprint('projects', __name__)


from app.projects import routes, images

src/app/projects/routes.py
"""

app/projects/routes.py

written by: Oliver Cordes 2019-02-04
changed by: Oliver Cordes 2020-03-29

"""

import os
from datetime import datetime

from flask import current_app, request, render_template, \
                  url_for, flash, redirect, send_file, \
                  make_response, jsonify
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.urls import url_parse
from werkzeug.utils import secure_filename


from app import db
from app.projects import bp
from app.projects.forms import CreateProjectForm, UpdateProjectForm, \
                               ProjectListForm, \
                               ManageBaseFileForm, ManageImageForm
from app.projects.admin import owner_required, check_access
from app.models import User, Project, \
                        File, FILE_BASE_FILE, \
                        Image
#from app.auth.email import send_password_reset_email, send_email_verify_email

from app.utils.files import size2human
from app.utils.backref import get_redirect_target



@bp.route('/project/<projectid>', methods=['GET','POST'])
@login_required
@owner_required('projectid')
def show_project(projectid):
    form = UpdateProjectForm(prefix='Update')

    project = Project.query.get(projectid)
    user    = User.query.get(project.user_id)

    if form.validate_on_submit():
        project.name = form.name.data
        project.is_public = form.is_public.data
        project.project_type = int(form.project_type.data)
        project.version = form.version.data
        db.session.commit()
        flash('Your changes have been saved.')
    else:
        form.name.default = project.name
        form.project_type.default = str(project.project_type)
        form.version.default = project.version
        form.is_public.default = project.is_public
        form.process()

    return render_template('projects/show_project.html',
                            title='Project \'{}\''.format(project.name),
                            form=form,
                            mform=ManageBaseFileForm(prefix='Manage'),
                            iform=ManageImageForm(prefix='Image'),
                            user=user,
                            readonly=user.id != project.user_id,
                            project=project,
                            size2human=size2human )


# upload_project_basefile
#
# adopted from:
# https://pythonise.com/categories/javascript/upload-progress-bar-xmlhttprequest

@bp.route('/project/basefile/<projectid>/add', methods=['POST'])
@login_required
@owner_required('projectid')
def upload_project_basefile(projectid):
    project = Project.query.get(projectid)
    user    = User.query.get(project.user_id)

    # get the file from the request
    f = request.files["file"]
    filename = secure_filename(f.filename)

    new_file = File.save_file(f, filename, FILE_BASE_FILE, project)

    db.session.add(new_file)
    db.session.commit()

    msg = 'Added \'{}\' to BaseFiles'.format(filename)

    res = make_response(jsonify({"message": msg}), 200)

    return res



@bp.route('/project/basefile/<projectid>/remove', methods=['POST'])
@login_required
@owner_required('projectid')
def remove_project_basefile(projectid):
    mform = ManageBaseFileForm(prefix='Manage')
    if mform.validate_on_submit():
        # get a list of selected items
        #selected_files = request.form.getlist('files')
        for id in request.form.getlist('files'):
            fid = File.query.get(id)
            ret, retmsg = fid.remove()
            if ret:
                # file was remove successfully
                # remove from database
                msg = 'Remove \'{}\' from BaseFiles'.format(fid.name)
                db.session.delete(fid)
            else:
                msg = 'Removing \'{}\' failed ({})'.format(fid.name, retmsg)
            flash(msg)
            current_app.logger.info(msg)
        db.session.commit()
    return redirect(url_for('projects.show_project', projectid=projectid))


@bp.route('/project/image/<projectid>/remove', methods=['POST'])
@login_required
@owner_required('projectid')
def remove_project_image(projectid):
    iform = ManageImageForm(prefix='Image')
    if iform.validate_on_submit():
        # get a list of selected items
        for id in request.form.getlist('images'):
            image = Image.query.get(id)
            ret, retmsg = image.remove()
            if ret:
                # image files were removed successfully
                # remove from database
                msg = 'Remove id=\'{}\' from Image'.format(id)
                db.session.delete(image)
            else:
                msg = 'Removing id=\'{}\' failed ({})'.format(id, retmsg)
            flash(msg)
            current_app.logger.info(msg)
        db.session.commit()
    return redirect(url_for('projects.show_project', projectid=projectid))



"""
get_project_file

provides the file with the original name (skipping the uuid-code!)
"""
@bp.route('/project/file/<projectid>/get/<fileid>', methods=['GET'])
@login_required
@owner_required('projectid')
def get_project_file(projectid,fileid):
    projectid = int(projectid)

    # look from which page we are called!
    target = get_redirect_target()

    project = Project.query.get(projectid)
    ffile = File.query.get(fileid)

    if ffile.project_id == projectid:
        filename = ffile.full_filename()
        orig_name = ffile.name[37:]
        return send_file(filename, as_attachment=True, attachment_filename=orig_name)
    else:
        msg = 'File doesn\'t match project ownership!'
        flash(msg)
        current_app.logger.info(msg)

    # back to caller
    return redirect(target)


@bp.route('/projects', methods=['GET','POST'])
@login_required
def show_projects():
    projects = None
    pr = Project.query.all()
    for p in pr:
        ret, msg = check_access(current_user, p)
        if ret:
            if projects is None:
                projects = [p]
            else:
                projects.append(p)
    form = ProjectListForm()
    if form.validate_on_submit():
        if form.create.data:
            return redirect(url_for('projects.create_project'))

        # get a list of selected items
        selected_projects = request.form.getlist('projects')
        for id in selected_projects:
            project = Project.query.get(id)
            ret, msgs = project.remove_files()
            if ret:
                db.session.delete(project)
                msg = 'remove project name={}'.format(project.name)
                current_app.logger.info(msg)
            else:
                for msg in msgs:
                    flash(msg)
                    current_app.logger.info(msg)
        db.session.commit()
        return redirect(url_for('projects.show_projects'))

    return render_template('projects/show_projects.html',
                            title='Project list',
                            projects=projects,
                            user_id=User.query.get,
                            form=form)


@bp.route('/project/add', methods=['GET','POST'])
@login_required
def create_project():
    form = CreateProjectForm()

    if form.validate_on_submit():
        project = Project(name=form.name.data,
                          is_public=form.is_public.data,
                          project_type=int(form.project_type.data),
                          version=form.version.data,
                          user_id=current_user.id,
                          status=0)
        db.session.add(project)
        db.session.commit()
        flash('Added project \'{}\''. format(project.name))
        #return redirect(url_for('main.index'))
        # refer to the new created project
        return redirect(url_for('projects.show_project',projectid=project.id))
    elif request.method == 'GET':
        # this is necessary, since WTF RadioField has no
        # default values ...
        form.project_type.default = str(0)
        form.process()
    return render_template('projects/create_project.html',
                            title='Create new project',
                            form=form)

src/app/templates/projects/create_project.html
{% extends "dashbase.html" %}

{% block app_content %}

<div class="card">
  <h5 class="card-header">Create a new project</h5>
  <div class="card-body">
    <form id="createprojectform" class="form-horizontal" role="form" method="post" action="">
      {{form.hidden_tag()}}
      <div class="input-group form-group">
        <div class="input-group-prepend">
          {{form.name.label(class_="input-group-text",style="width:150px")}}
        </div>
        {{form.name(class_="form-control",placeholder="Name")}}
        {% if form.name.errors|length > 0 %}
        <div id="signupalert" class="alert alert-danger">
          {% for error in form.name.errors %}
          <span>{{error}}</span>
          {% endfor %}
        </div>
        {% endif %}
      </div>
      <div class="input-group form-group">
        <div class="input-group-prepend">
          {{form.project_type.label(class_="input-group-text",style="width:150px")}}
        </div>
        {% for subfield in form.project_type %}
        <div class="input-group-text">
          {{subfield()}}
        </div>
        {{subfield.label(class_="input-group-text")}}
        {% endfor %}
      </div>
      <div class="input-group form-group">
        <div class="input-group-prepend">
          {{form.version.label(class_="input-group-text",style="width:150px")}}
        </div>
        {{form.version(class_="form-control")}}
      </div>
      <div class="input-group form-group">
        <div class="input-group-prepend">
          <div class="input-group-text" style="width:150px">
            Visibility
          </div>
        </div>
        <div class="input-group-text">
          {{ form.is_public }}
        </div>
        {{form.is_public.label(class_="input-group-text")}}
      </div>
      <div class="input-group form-group">
        {{form.submit(class_="btn btn-info", id="btn-submit")}}
      </div>
    </form>
  </div>
</div>

{% endblock %}

src/app/templates/projects/show_image.html
{% extends "dashbase.html" %}

{% block app_content %}

<div class="card">
  <img class="card-img-top" src="{{image.owner.avatar(128)}}" style="width: 128px;" alt="Avatar">
  <div class="card-body">
    <h1 class="card-title">{{image.owner.first_name}} {{image.owner.last_name}}</h1>
    <p class="card-text">({{image.owner.username}})</p>
  </div>
</div>


<div class="card mt-3">
  <div class="card-body">
    <div class="row">
      <div class="col-2">
        Created:
      </div>
      <div class="col-10">
        {{image.created.strftime('%Y-%m-%d %H:%M:%S')}}
      </div>
    </div>
    <div class="row">
      <div class="col-2">
        Project:
      </div>
      <div class="col-10">
        <a href="{{url_for('projects.show_project',projectid=image.project_id)}}">{{image.project.name}}</a>
      </div>
    </div>
    <div class="row">
      <div class="col-2">
        Status:
      </div>
      <div class="col-10">
        {% if image.error_code is none or image.error_code == 0 %}
        {{image.state2str}}
        {% else %}
        <span style="color:red">{{image.state2str}} (Error)</span>
        {% endif %}
      </div>
    </div>
    {% if image.state == image.IMAGE_STATE_FINISHED %}
    <div class="row">
      <div class="col-2">
        Finished:
      </div>
      <div class="col-2">
        {{image.finished.strftime('%Y-%m-%d %H:%M:%S')}}
      </div>
      <div class="col-2">
        Error code:
      </div>
      <div class="col-6">
        {% if image.error_code == 0 %}
        {{image.error_code}}
        {% else %}
        <span style="color:red"><b>{{image.error_code}}</b></span>
        {% endif %}
      </div>
    </div>
    <div class="row">
      <div class="col-2">
        Process time:
      </div>
      <div class="col-10">
        {{'%0.3f'|format((image.finished-image.requested).total_seconds())}}s
      </div>
    </div>
    {% endif %}
  </div>
</div>

{% if image.render_image != -1 %}
<div class="card mt-3">
  <h5 class="card-header">Rendered image</h5>
  <div class="card-body">
    <div class="row">
      <div class="col-2">
        Image size:
      </div>
      <div class="col-10">
        {{image.im_width()}}x{{image.im_height()}} pixels
      </div>
    </div>
    <div class="row mt-3">
      <a href="{{url_for('projects.get_render_image',imageid=image.id)}}">
        <img class="col-12" src="{{url_for('projects.get_render_icon',imageid=image.id)}}">
      </a>
    </div>
    <div class="row mt-3">
      {% if has_flickr %}
      <div class="col-2">
        <form id="uploadform" class="form-horizontal" role="form" method="post" action="{{url_for('social.flickr_upload')}}">
          {{uform.hidden_tag()}}
        </form>
        <button id="flickr_btn" class="btn btn-info" form="uploadform">
          <i class="fab fa-flickr"></i> flickr upload
        </button>
      </div>
      {%endif%}
      <div class="col-2">
        <form id="uploadform2" class="form-horizontal" role="form" method="post" action="{{url_for('social.piwigo_upload')}}">
          {{uform2.hidden_tag()}}
        </form>
        <button id="flickr_btn" class="btn btn-info" form="uploadform2">
          <i class="fa fa-image"></i> Piwigo upload
        </button>
      </div>
    </div>

  </div>
</div>
{% endif %}

{% if image.log_file != -1 %}
<div class="card mt-3">
  <h5 class="card-header">Logfile</h5>
  <div class="card-body">
    <div class="row">
      <div class="col-12">
        <pre class="pre-scrollable">{{logfile_data}}
        </pre>
      </div>
    </div>
  </div>
</div>
{% endif %}

<div class="card mt-3">
  <h5 class="card-header">Downloads</h5>
  <div class="card-body">
    <div class="row">
      <div class="col-2">
        Model:
      </div>
      <div class="col-10">
        <a href="{{url_for('projects.get_project_file',projectid=image.project_id,fileid=image.model)}}">{{image.model}}</a>
      </div>
    </div>
    <div class="row">
      <div class="col-2">
        Rendered image:
      </div>
      <div class="col-10">
        {% if image.render_image == -1 %}
        Unavailable
        {% else %}
        <a href="{{url_for('projects.get_project_file',projectid=image.project_id,fileid=image.render_image)}}">{{image.render_image}}</a>
        {% endif %}
      </div>
    </div>
    <div class="row">
      <div class="col-2">
        Log file:
      </div>
      <div class="col-10">
        {% if image.log_file == -1 %}
        Unavailable
        {% else %}
        <a href="{{url_for('projects.get_project_file',projectid=image.project_id,fileid=image.log_file)}}">{{image.log_file}}</a>
        {% endif %}
      </div>
    </div>
  </div>
</div>


{% endblock %}

src/app/templates/projects/show_projects.html
{% extends "dashbase.html" %}

{% block app_content %}


<div class="card">
  <h5 class="card-header">List of available projects</h5>
  <div class="card-body">
    <form id="projectsform" class="form-horizontal" role="form" method="post" action="">
      {{form.hidden_tag()}}
      <div class="d-flex justify-content-end">
        {{ form.create(class_="btn btn-info m-3")}}
      </div>
      <div class="table-responsive">
        <table class="table table-bordered">
          <thead>
            <td></td>
            <td>ID</td>
            <td>Name</td>
            <td>Owner</td>
            <td>Type</td>
            <td>Version</td>
            <td>Public</td>
            <td>Status</td>
            <td>Created</td>
          </thead>
          {% if projects is none %}
          <tr>
            <td colspan="4">No projects</td>
          </tr>
          {% else %}
          {% for project in projects %}
          <tr>
            <td>
              <input type="checkbox" name="projects" value="{{project.id}}">
            </td>
            <td><a href="{{url_for('projects.show_project', projectid=project.id)}}">{{project.id}}</a></td>
            <td><a href="{{url_for('projects.show_project', projectid=project.id)}}">{{project.name}}</a></td>
            <td>{{user_id(project.user_id).username}}</td>
            {% if project.project_type == 0 %}
            <td>Image</td>
            {% else %}
            <td>Animation</td>
            {% endif %}
            <td>{{project.version}}</td>
            <td>{{project.is_public}}</td>
            <td>{{project.state2str}}</td>
            <td>{{project.timestamp.strftime('%Y-%m-%d %H:%M')}}</td>
          </tr>
          {% endfor %}
          {% endif %}
        </table>
      </div>
      {{form.remove(class_="btn btn-danger",onclick="return (doStuff())")}}
    </form>
  </div>
</div>



<script>
function doStuff(){
  return (confirm('Do you really want to remove these items?'))
}
</script>
{% endblock %}